services:
  uaipydb:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env

  api:
    build: .
    depends_on:
      - uaipydb
      - mosquitto

    ports:
      - "8000:8000"
    env_file:
      - .env

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883" 
    volumes:
    - ./mosquitto/config:/mosquitto/config
    - ./mosquitto/data:/mosquitto/data
    - ./mosquitto/log:/mosquitto/log
    restart: always

  mqtt_consumer:
    build: .
    depends_on:
      - mosquitto
      - uaipydb
    command: ["python", "run_mqtt_consumer.py"]
    env_file:
      - .env

volumes:
  pgdata:
  mosquitto_data:
  mosquitto_config: